# Mandatory settings

name: trader
paginate: 100
url: https://trader0731.github.io
ga_analytics: G-JKZX03LHFF

# Important settings (change at own risk)

# 新的Sass配置
sass:
  sass_dir: assets/css
  style: compressed

collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
      encoding: utf-8
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - vendor/
  - yarn.lock
  - 说明.md
plugins:
  - jekyll-paginate
paginate_path: /posts/page/:num/
permalink: posts/:slug
encoding: utf-8
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false