# Mandatory settings

name: shaoting
url: https://gushaoting.com
ga_analytics: G-6Y0933ZC8T

# Important settings (change at own risk)

sass:
  sass_dir: assets/css
  style: compressed

collections:
  my_tags:
    output: true
    permalink: /tag/:slug/

tag_order:
  - 结构研究系列
  - 诗
  - 小说


defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
      encoding: utf-8
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/

plugins: []

permalink: posts/:slug
encoding: utf-8
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true